max_width = 80
reorder_imports = true
blank_lines_upper_bound = 2
wrap_comments = true
condense_wildcard_suffixes = true
edition = '2018'
error_on_unformatted = true
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
merge_imports = true
tab_spaces = 2
